# Generated by Django 2.1.1 on 2019-11-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(verbose_name=(1, 2, 3, 4)),
        ),
    ]
